version: '2'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '80:3000'
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes: ['~/mongo/data:/data/db']
    ports:
      - '27018:27017'
